project:
  type: website
  output-dir: _site

website:
  title: "The Thinking Experiment"
  navbar:
    right:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/vladimirlopez/the-thinking-experiment
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



