project:
  type: website
  output-dir: _site

website:
  title: "The Thinking Experiment"
  site-url: https://vladimirlopez.github.io/the-thinking-experiment
  google-analytics: "G-JBQ9ZQLYSX"
  favicon: assets/favicon.png
  navbar:
    search: true
    right:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Topics"
        menu:
          - text: "Physics"
            href: "#"
          - text: "AI in Teaching" 
            href: "#"
          - text: "Coding Workflows"
            href: "#"
      - icon: github
        href: https://github.com/vladimirlopez/the-thinking-experiment
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true
    toc-location: right
    reading-time: true
    include-in-header:
      - text: |
          <meta property="og:site_name" content="The Thinking Experiment">
          <meta property="og:type" content="website">
          <meta name="twitter:card" content="summary_large_image">
          <meta name="twitter:creator" content="@vladimirlopez">
    include-after-body: _includes/comments.html
    open-graph: true
    twitter-card: true



