project:
  type: website
  output-dir: _site

website:
  title: "The Thinking Experiment"
  site-url: https://vladimirlopez.github.io/the-thinking-experiment
  description: "AI, education, and physics—experiments, notes, and tools."
  image: assets/tte-logo.png
  feed: true
  google-analytics: "G-JBQ9ZQLYSX"
  favicon: assets/favicon.png
  navbar:
    search: true
    right:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Lab Notebook"
        href: lab-notebook.qmd
      - text: "Prompt Library"
        href: prompt-library.qmd
      - text: "Topics"
        href: topics.qmd
      - icon: github
        href: https://github.com/vladimirlopez/the-thinking-experiment
      - icon: linkedin
        href: https://www.linkedin.com/in/vladimirglopez

format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true
    toc-location: right
    reading-time: true
    math: none
    include-in-header:
      - text: |
          <meta property="og:site_name" content="The Thinking Experiment">
          <meta property="og:type" content="website">
          <meta name="twitter:card" content="summary_large_image">
          <meta name="twitter:creator" content="@vladimirlopez">
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-16.png">
          <link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
          <link rel="manifest" href="site.webmanifest">
      - text: |
          <script type="application/ld+json">
          {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "The Thinking Experiment",
            "url": "https://vladimirlopez.github.io/the-thinking-experiment",
            "potentialAction": {
              "@type": "SearchAction",
              "target": "https://vladimirlopez.github.io/the-thinking-experiment/search.html?q={search_term_string}",
              "query-input": "required name=search_term_string"
            }
          }
          </script>
    include-after-body:
      - text: |
          <script>
          // Basic outbound link tracking via gtag
          (function(){
            function isExternal(url){
              try { var u = new URL(url, window.location.href); return u.origin !== window.location.origin; } catch(e){ return false; }
            }
            document.addEventListener('click', function(e){
              var a = e.target.closest('a[href]');
              if (!a) return;
              if (isExternal(a.href) && typeof gtag === 'function') {
                gtag('event', 'click', {
                  'event_category': 'outbound',
                  'event_label': a.href,
                  'transport_type': 'beacon'
                });
              }
            }, true);
          })();
          </script>
    # Comments now scoped to posts via posts/_metadata.yml
    # include-after-body removed here to avoid site-wide load
    open-graph: true
    twitter-card: true

