project:
  type: website
  output-dir: _site

website:
  title: "The Thinking Experiment"
  site-url: https://vladimirlopez.github.io/the-thinking-experiment
  google-analytics: "G-JBQ9ZQLYSX"
  navbar:
    search: true
    right:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Topics"
        menu:
          - text: "Physics"
            href: "#"
          - text: "AI in Teaching" 
            href: "#"
          - text: "Coding Workflows"
            href: "#"
      - icon: github
        href: https://github.com/vladimirlopez/the-thinking-experiment
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true
    toc-location: right
    reading-time: true



